### ISSUE TITLE
Whether to change hosts

### ISSUE THREAD

**Issue by IT-LiuSir** [openziti/ziti-sdk-swift#196]
In an Intranet environment, MacOS and Windows need to configure hosts and resolve the hosts address before connecting to the controller and routing. Is this correct? If so, how to configure iOS and Android

**Comment by dovholuknf** [comment]
This seems like a generic question that might be better suited to the discourse: https://openziti.discourse.group/.

I'm not quite sure I understand what "configure hosts and resolve the hosts address" means. If you mean that your controller and edge router need to be somewhere out on the internet, so that your windows and macos clients can connect to the controller and router, then yes. that would be necessary. Hope that helps. Reopen this issue if needed or perhaps post over on discourse for more discussion (more people watch the discourse)
